# Generated by Django 4.1.2 on 2022-11-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0002_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='掲示板の投稿内容', max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
